### ISSUE TITLE
Tests files should be max 10MB

### ISSUE THREAD

**Issue by OneVoltTen** [CXwudi/Niconico-Video-Downloader#28]
Should reduce the size of the test files, 97MB is a bit excessive.

**Comment by CXwudi** [comment]
Hi, thanks for your advice. But the project is not i active development.

**Comment by OneVoltTen** [comment]
Yes, I had closed it after reading it was inactive.

**Comment by CXwudi** [comment]
Yeah, anyways if you are looking for downloading niconico videos. U can check my youtube-dl folk or the folk from animelover1984
